### ISSUE TITLE
Archive Abandoned Project?

### ISSUE THREAD

**Issue by sysrage** [1j01/nw-dev#10]
Since this repo hasn't been updated in 6+ years, I recommend archiving it and creating a new "nwcli" type tool that integrates some of the functionality discussed here: https://github.com/nwutils/nw-builder/issues/623

After archiving, this repo would still be readable for reference purposes. However, it'll be obvious that it's an abandoned project (especially if the README gets a quick update, too).

**Comment by 1j01** [comment]
Well, I haven't used NW.js in a long time, but I could still do some basic maintenance on this.
I may archive it when I see a clear alternative, that I would use instead of nw-dev.
I'm not sure it's a one-size-fits-all situation, and a CLI might not provide the same flexibility if you have multiple browser windows with different concerns. And if it does, it won't be as simple, for the same features.

**Comment by TheJaredWilcurt** [comment]
I would prefer no repo be archived. If it is no longer maintained, then that should just be noted at the top of the README, as "Not maintained" or "Deprecated". But otherwise the repo could live on and still allow people to create and comment on issues (archiving prevents this).

The only time I think archiving makes sense is if you are moving a repo from one platform to another (GitHub, GitLab, BitBucket, etc), then linking to the new location from the old before archiving. But otherwise, it's better to let people still interact with the project. Many may just need to ask a question, and others could answer those questions. better to keep all that knowledge in the place people will be looking for it.

**Comment by sysrage** [comment]
Per consensus, abandoned projects won't be archived.
